"""empty message

Revision ID: 297660152905
Revises: 
Create Date: 2026-06-16 12:05:01.850051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '297660152905'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(), nullable=True),
    sa.Column('car_model', sa.String(), nullable=True),
    sa.Column('car_year', sa.String(), nullable=True),
    sa.Column('horse_power', sa.Integer(), nullable=True),
    sa.Column('top_speed', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('car_color', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('car_price', sa.Float(), nullable=True),
    sa.Column('car_type', sa.String(), nullable=True),
    sa.Column('information', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_images')
    op.drop_table('cars')
    # ### end Alembic commands ###
